# Generated by Django 6.1.1 on 2026-10-02 04:43

import django.contrib.gis.db.models.functions
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=django.contrib.postgres.indexes.GistIndex(django.contrib.gis.db.models.functions.Transform('location', 5070), name='station_location_albers_idx'),
        ),
    ]
