# Generated by Django 6.1.1 on 2026-10-01 20:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gazetteer', 'Census Gazetteer'), ('gnis', 'USGS GNIS'), ('alias', 'Manual alias')], max_length=16)),
                ('source_id', models.CharField(max_length=32)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('name_normalized', models.CharField(max_length=120)),
                ('name_key', models.CharField(max_length=120)),
                ('place_type', models.CharField(blank=True, max_length=4)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('land_area_sqmi', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(spatial_index=False, srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'name_normalized'], name='place_state_name_idx'), models.Index(fields=['state', 'name_key'], name='place_state_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='place_unique_source_id')],
            },
        ),
    ]
