# Generated by Django 6.1.1 on 2026-10-02 07:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('usps', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
