# Generated by Django 6.1.1 on 2026-10-02 05:02

import django.contrib.gis.db.models.fields
import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_label', models.CharField(max_length=120)),
                ('destination_label', models.CharField(max_length=120)),
                ('origin', django.contrib.gis.db.models.fields.PointField(spatial_index=False, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(spatial_index=False, srid=4326)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(spatial_index=False, srid=4326)),
                ('distance_miles', models.DecimalField(decimal_places=1, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('max_range_miles', models.DecimalField(decimal_places=1, max_digits=6)),
                ('mpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stops', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('total_gallons', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('routing_provider', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
