# Generated by Django 6.1.1 on 2026-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='initial_fuel_gallons',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
