# Generated by Django 6.1.1 on 2026-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_initial_fuel_gallons'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='baseline_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='baseline_stops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='corridor_miles',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=4),
        ),
    ]
