# Generated by Django 6.1.1 on 2026-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_baseline_and_corridor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_fuel_gallons',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_ledger',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='initial_fuel_price_per_gallon',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
